#!/usr/bin/env bash

set -euo pipefail

usage_common() {
  cat <<'EOF'
Common helper for main-based agent/integration worktree setup.
EOF
}

port_in_use() {
  local port="$1"
  lsof -nP -iTCP:"${port}" -sTCP:LISTEN >/dev/null 2>&1
}

dev_port_base_for_kind() {
  local kind="$1"
  case "${kind}" in
    codex) echo 3100 ;;
    claude) echo 3200 ;;
    gemini) echo 3300 ;;
    integration) echo 3400 ;;
    *) echo 3500 ;;
  esac
}

api_port_base_for_kind() {
  local kind="$1"
  case "${kind}" in
    codex) echo 8100 ;;
    claude) echo 8200 ;;
    gemini) echo 8300 ;;
    integration) echo 8400 ;;
    *) echo 8500 ;;
  esac
}

task_hash_offset() {
  local task_slug="$1"
  cksum <<<"${task_slug}" | awk '{ print $1 % 100 }'
}

assign_dev_port() {
  local kind="$1"
  local task_slug="$2"
  local base port attempts
  base="$(dev_port_base_for_kind "${kind}")"
  port=$(( base + $(task_hash_offset "${task_slug}") ))
  attempts=0

  while port_in_use "${port}"; do
    port=$(( port + 1 ))
    attempts=$(( attempts + 1 ))
    if [[ "${attempts}" -gt 50 ]]; then
      echo "Error: could not find an available dev port near ${base}." >&2
      exit 1
    fi
  done

  echo "${port}"
}

assign_api_port() {
  local kind="$1"
  local task_slug="$2"
  local base port attempts
  base="$(api_port_base_for_kind "${kind}")"
  port=$(( base + $(task_hash_offset "${task_slug}") ))
  attempts=0

  while port_in_use "${port}"; do
    port=$(( port + 1 ))
    attempts=$(( attempts + 1 ))
    if [[ "${attempts}" -gt 50 ]]; then
      echo "Error: could not find an available api port near ${base}." >&2
      exit 1
    fi
  done

  echo "${port}"
}

read_env_value() {
  local env_path="$1"
  local key="$2"

  if [[ ! -f "${env_path}" ]]; then
    return 1
  fi

  awk -F= -v target="${key}" '
    $0 ~ "^[[:space:]]*#" { next }
    $1 == target {
      sub(/^[^=]+= */, "", $0)
      print $0
      exit
    }
  ' "${env_path}"
}

ensure_git_repo() {
  if ! git rev-parse --show-toplevel >/dev/null 2>&1; then
    echo "Error: current directory is not inside a git repository." >&2
    exit 1
  fi
}

repo_root() {
  git rev-parse --show-toplevel
}

repo_name() {
  basename "$(repo_root)"
}

coordination_root() {
  dirname "$(git rev-parse --path-format=absolute --git-common-dir)"
}

bootstrap_web_env_for_worktree() {
  local worktree_path="$1"
  local kind="$2"
  local task_slug="$3"
  local web_dir source_env target_env supabase_url supabase_anon admin_emails api_base_url dev_port api_port

  web_dir="${worktree_path}/apps/web"
  source_env="$(coordination_root)/.env.development"
  target_env="${web_dir}/.env.development.local"

  if [[ ! -d "${web_dir}" ]]; then
    return 0
  fi

  supabase_url="$(read_env_value "${source_env}" "SUPABASE_URL" || true)"
  supabase_anon="$(read_env_value "${source_env}" "SUPABASE_ANON_KEY" || true)"
  admin_emails="$(read_env_value "${source_env}" "PROMPTOPS_ADMIN_EMAILS" || true)"
  dev_port="$(assign_dev_port "${kind}" "${task_slug}")"
  api_port="$(assign_api_port "${kind}" "${task_slug}")"
  api_base_url="http://localhost:${api_port}"

  cat > "${target_env}" <<EOF
# Auto-generated by scripts/start_agent_task.sh or scripts/start_integration_task.sh.
# Safe to regenerate. Do not store secrets here.
PORT=${dev_port}
FASTAPI_PORT=${api_port}
NEXT_PUBLIC_API_BASE_URL=${api_base_url}
NEXT_PUBLIC_SUPABASE_URL=${supabase_url}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${supabase_anon}
PROMPTOPS_ADMIN_EMAILS=${admin_emails}
PROMPTOPS_DEV_BYPASS=true
EOF

  printf 'web_env_bootstrap=%s\n' "${target_env}"
  printf 'web_dev_port=%s\n' "${dev_port}"
}

ensure_branch_exists() {
  local branch="$1"
  if ! git show-ref --verify --quiet "refs/heads/${branch}"; then
    echo "Error: base branch '${branch}' does not exist locally." >&2
    echo "Hint: fetch or create the branch locally, then retry." >&2
    exit 1
  fi
}

warn_if_dirty() {
  if [[ -n "$(git status --porcelain)" ]]; then
    echo "Warning: current worktree has uncommitted changes. Continue carefully." >&2
  fi
}

validate_task_slug() {
  local task_slug="$1"
  if [[ -z "${task_slug}" ]]; then
    echo "Error: --task is required." >&2
    exit 1
  fi

  case "${task_slug}" in
    *[!A-Za-z0-9._-]*)
      echo "Error: task slug must match [A-Za-z0-9._-]." >&2
      exit 1
      ;;
  esac
}

validate_agent() {
  local agent="$1"
  case "${agent}" in
    codex|claude|gemini) ;;
    *)
      echo "Error: --agent must be one of: codex, claude, gemini." >&2
      exit 1
      ;;
  esac
}

branch_name_for_agent() {
  local agent="$1"
  local task_slug="$2"
  printf '%s/%s\n' "${agent}" "${task_slug}"
}

branch_name_for_integration() {
  local task_slug="$1"
  printf 'integration/%s\n' "${task_slug}"
}

worktree_path_for_kind() {
  local kind="$1"
  local task_slug="$2"
  local root
  root="$(repo_root)"
  printf '%s/%s-worktrees/%s/%s\n' "$(dirname "${root}")" "$(repo_name)" "${kind}" "${task_slug}"
}

existing_worktree_for_branch() {
  local branch="$1"
  git worktree list --porcelain | awk -v target="refs/heads/${branch}" '
    $1 == "worktree" { current=$2 }
    $1 == "branch" && $2 == target { print current; exit }
  '
}

print_result() {
  local base_branch="$1"
  local target_branch="$2"
  local worktree_path="$3"
  local root
  root="$(repo_root)"

  cat <<EOF
base_branch=${base_branch}
target_branch=${target_branch}
worktree_path=${worktree_path}
next_command=cd ${worktree_path}
EOF

  cat >&2 <<EOF
notice=execution_worktree_ready
coordination_root=${root}
canonical_docs_policy=edit_docs_in_root_repo
EOF
}

ensure_parent_dir() {
  local worktree_path="$1"
  mkdir -p "$(dirname "${worktree_path}")"
}

create_or_reuse_worktree() {
  local branch="$1"
  local worktree_path="$2"
  local base_branch="$3"

  local existing_worktree
  existing_worktree="$(existing_worktree_for_branch "${branch}")"
  if [[ -n "${existing_worktree}" ]]; then
    print_result "${base_branch}" "${branch}" "${existing_worktree}"
    return 0
  fi

  if [[ -e "${worktree_path}" && ! -d "${worktree_path}" ]]; then
    echo "Error: target worktree path exists and is not a directory: ${worktree_path}" >&2
    exit 1
  fi

  ensure_parent_dir "${worktree_path}"

  if git show-ref --verify --quiet "refs/heads/${branch}"; then
    git worktree add "${worktree_path}" "${branch}" >/dev/null
  else
    git worktree add -b "${branch}" "${worktree_path}" "${base_branch}" >/dev/null
  fi

  print_result "${base_branch}" "${branch}" "${worktree_path}"
}
